In [66]:
import  numpy as np
np.random.seed(2023)
nd1 = np.random.random([10])
# nd1[x:y:z] x: start index, y: end index, z: step
print(
    '\n', 'nd1:', '\n', nd1, '\n',
    '\n', 'nd1[3]:', '\n', nd1[3], '\n',
    '\n', 'nd1[3:6]:', '\n', nd1[3:6], '\n',
    '\n', 'nd1[1:6:2]:', '\n', nd1[1:6:2], '\n',
    '\n', 'nd1[::2]:', '\n', nd1[::2], '\n',
    '\n', 'nd1[::-2]:', '\n', nd1[::-2], '\n'
)


 nd1: 
 [0.3219883  0.89042245 0.58805226 0.12659609 0.14134122 0.46789559
 0.02208966 0.72727471 0.52438734 0.54493524] 
 
 nd1[3]: 
 0.12659609350429124 
 
 nd1[3:6]: 
 [0.12659609 0.14134122 0.46789559] 
 
 nd1[1:6:2]: 
 [0.89042245 0.12659609 0.46789559] 
 
 nd1[::2]: 
 [0.3219883  0.58805226 0.14134122 0.02208966 0.52438734] 
 
 nd1[::-2]: 
 [0.54493524 0.72727471 0.46789559 0.12659609 0.89042245] 



In [67]:
nd2 = np.arange(30).reshape([5, 6])
print(
    '\n', 'nd2:', '\n', nd2, '\n',
    '\n', 'nd2[1, 3]:', '\n', nd2[1, 3], '\n',
    '\n', 'nd2[[1, 3], [1, 3]]:', '\n', nd2[[1,3], [1,3]], '\n',
    '\n', 'nd2[1:3]:', '\n', nd2[1:3], '\n',
    '\n', 'nd2[1:3, 1:3]:', '\n', nd2[1:3, 1:3], '\n',
    '\n', 'nd2[(nd2>3)&(nd2<10)]:', '\n', nd2[(nd2>3)&(nd2<10)], '\n',
    '\n', 'nd2[1:6:2]:', '\n', nd2[1:6:2], '\n',
    '\n', 'nd2[::2]:', '\n', nd2[::2], '\n',
    '\n', 'nd2[::-2]:', '\n', nd2[::-2], '\n'
)


 nd2: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 
 
 nd2[1, 3]: 
 9 
 
 nd2[[1, 3], [1, 3]]: 
 [ 7 21] 
 
 nd2[1:3]: 
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 
 
 nd2[1:3, 1:3]: 
 [[ 7  8]
 [13 14]] 
 
 nd2[(nd2>3)&(nd2<10)]: 
 [4 5 6 7 8 9] 
 
 nd2[1:6:2]: 
 [[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]] 
 
 nd2[::2]: 
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [24 25 26 27 28 29]] 
 
 nd2[::-2]: 
 [[24 25 26 27 28 29]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]] 



In [68]:
import numpy as np
from numpy import random as nr
a = np.arange(1, 25, dtype=float)
# 随机可重复抽取
c1 = nr.choice(a, size=(3,4))
print(c1)
# 随机不可重复抽取
c2 = nr.choice(a, size=(3,4), replace=False)
print(c2)
c3 = nr.choice(a, size=(3,4), p=a/np.sum(a))
print(c3)

[[19.  4. 18. 15.]
 [17.  8. 18. 17.]
 [ 1. 18.  9. 18.]]
[[ 1.  4. 10.  3.]
 [23. 13. 14. 11.]
 [ 6. 20.  8.  2.]]
[[22. 22. 24. 23.]
 [ 8. 22. 14. 13.]
 [16. 18. 19.  7.]]
