In [53]:
import  numpy as np
list1 = [3.3, 2.5, 0, 1, 2]
nd1 = np.array(list1)
print('nd1:\n', nd1, '\n', type(nd1))

nd1:
 [3.3 2.5 0.  1.  2. ] 
 <class 'numpy.ndarray'>


In [54]:
list2 = [[3.3, 2.5, 0, 1, 2], [3.3, 2.5, 0, 1, 2]]
nd2 = np.array(list2)
print('nd2:\n', nd2, '\n', type(nd2))

nd2:
 [[3.3 2.5 0.  1.  2. ]
 [3.3 2.5 0.  1.  2. ]] 
 <class 'numpy.ndarray'>


In [55]:
nd3 = np.random.random([3, 3])
print('nd3:\n', nd3, '\n', type(nd3), '\n', nd3.shape)

nd3:
 [[0.02798196 0.17390652 0.15408224]
 [0.07708648 0.8898657  0.7503787 ]
 [0.69340324 0.51176338 0.46426806]] 
 <class 'numpy.ndarray'> 
 (3, 3)


In [56]:
np.random.seed(123)
nd4 = np.random.randn(2, 3)
print('nd4:\n', nd4)
np.random.shuffle(nd4)
print('nd4:\n', nd4, '\n', type(nd4), '\n', nd4.shape)

nd4:
 [[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
nd4:
 [[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]] 
 <class 'numpy.ndarray'> 
 (2, 3)


In [57]:
nd5 = np.zeros([3, 3])
np.zeros_like(nd5)
print('nd5:\n', nd5, '\n', type(nd5), '\n', nd5.shape)

nd6 = np.ones([3, 3])
# np.ones_like(nd6)
print('nd6:\n', nd6, '\n', type(nd6), '\n', nd6.shape)

nd7 = np.eye(9)
print('nd7:\n', nd7, '\n', type(nd7), '\n', nd7.shape)

nd8 = np.diag([1, 2, 3, 4, 5])
print('nd8:\n', nd8, '\n', type(nd8), '\n', nd8.shape)

nd5:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 <class 'numpy.ndarray'> 
 (3, 3)
nd6:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 <class 'numpy.ndarray'> 
 (3, 3)
nd7:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]] 
 <class 'numpy.ndarray'> 
 (9, 9)
nd8:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]] 
 <class 'numpy.ndarray'> 
 (5, 5)


In [58]:
nd9 = np.random.random([5, 5])
np.savetxt(X=nd9, fname='nd9.txt', fmt='%.2f', delimiter=',')
print('nd9:\n', nd9, '\n', type(nd9), '\n', nd9.shape)

nd9:
 [[0.41092437 0.5796943  0.13995076 0.40101756 0.62731701]
 [0.32415089 0.24475928 0.69475518 0.5939024  0.63179202]
 [0.44025718 0.08372648 0.71233018 0.42786349 0.2977805 ]
 [0.49208478 0.74029639 0.35772892 0.41720995 0.65472131]
 [0.37380143 0.23451288 0.98799529 0.76599595 0.77700444]] 
 <class 'numpy.ndarray'> 
 (5, 5)


In [59]:
nd10 = np.loadtxt('nd9.txt', delimiter=',')
print('nd10:\n', nd10, '\n', type(nd10), '\n', nd10.shape)

nd10:
 [[0.41 0.58 0.14 0.4  0.63]
 [0.32 0.24 0.69 0.59 0.63]
 [0.44 0.08 0.71 0.43 0.3 ]
 [0.49 0.74 0.36 0.42 0.65]
 [0.37 0.23 0.99 0.77 0.78]] 
 <class 'numpy.ndarray'> 
 (5, 5)


In [60]:
nd11 = np.arange(10)
print('nd11:\n', nd11, '\n', type(nd11), '\n', nd11.shape)
nd12 = np.arange(0, 10)
print('nd12:\n', nd12, '\n', type(nd12), '\n', nd12.shape)
nd13 = np.arange(0, 6, 0.5)
print('nd13:\n', nd13, '\n', type(nd13), '\n', nd13.shape)
nd14 = np.arange(9, -1, -1)
print('nd14:\n', nd14, '\n', type(nd14), '\n', nd14.shape)

nd11:
 [0 1 2 3 4 5 6 7 8 9] 
 <class 'numpy.ndarray'> 
 (10,)
nd12:
 [0 1 2 3 4 5 6 7 8 9] 
 <class 'numpy.ndarray'> 
 (10,)
nd13:
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5] 
 <class 'numpy.ndarray'> 
 (12,)
nd14:
 [9 8 7 6 5 4 3 2 1 0] 
 <class 'numpy.ndarray'> 
 (10,)


In [61]:
nd15 = np.linspace(0, 1, 5)
print('nd15:\n', nd15, '\n', type(nd15), '\n', nd15.shape)

nd15:
 [0.   0.25 0.5  0.75 1.  ] 
 <class 'numpy.ndarray'> 
 (5,)
